-- 046b: Seed futsal venues (269 rows from 한국풋살연맹)
INSERT INTO public.venues (sport, name, region, region_code, address, venue_type, court_count, phone, website, source, verified_at)
VALUES
  ('futsal', '용산 더베이스 풋살장', '서울시', 'seoul_metro', '용산구 한강로 23길 55 현대아이파크몰', 'mixed', 8, '02-2012-3810', 'https://www.iparkmall.co.kr/thebase/intro.do', 'futsal.or.kr', now()),
  ('futsal', '잠실무브풋살파크', '서울시', 'seoul_metro', '송파구 올림픽로 25길 종합운동장내', 'outdoor', 3, '02-2240-8783', 'https://stadium.seoul.go.kr/', 'futsal.or.kr', now()),
  ('futsal', '반야트리호텔 풋살장(회원제)', '서울시', 'seoul_metro', '중구 장충단로 60', 'outdoor', 1, '02-2250-8080', NULL, 'futsal.or.kr', now()),
  ('futsal', '황금내 근린공원풋살장', '서울시', 'seoul_metro', '강서구 염창동 227-1', 'outdoor', 1, '무료', NULL, 'futsal.or.kr', now()),
  ('futsal', '응봉체육공원풋살장', '서울시', 'seoul_metro', '성동구 응봉동 235', 'outdoor', 1, '02-2204-7650', 'https://sports.happysd.or.kr/', 'futsal.or.kr', now()),
  ('futsal', '홍싸커 & 실내풋살장', '서울시', 'seoul_metro', '강동구 동남로 891 현대델리안오피스텔', 'indoor', 1, '010-3350-3698', NULL, 'futsal.or.kr', now()),
  ('futsal', '미양고등학교풋살장', '서울시', 'seoul_metro', '강북구 인수봉로 39', 'outdoor', 1, '02-982-6104', NULL, 'futsal.or.kr', now()),
  ('futsal', '미양중학교풋살장', '서울시', 'seoul_metro', '강북구 인수봉로 39', 'outdoor', 1, NULL, NULL, 'futsal.or.kr', now()),
  ('futsal', '우장산축구장', '서울시', 'seoul_metro', '강서구 화곡로 302', 'outdoor', 1, '02-2600-4195', NULL, 'futsal.or.kr', now()),
  ('futsal', '난우중학교풋살장', '서울시', 'seoul_metro', '관악구 난곡로 16길 32', 'outdoor', 1, '02-864-4017', NULL, 'futsal.or.kr', now()),
  ('futsal', '아차산배수지체육공원풋살장', '서울시', 'seoul_metro', '광진구 구의동', 'outdoor', 2, '02-3437-7234', NULL, 'futsal.or.kr', now()),
  ('futsal', '서울어린이대공원풋살장', '서울시', 'seoul_metro', '광진구 능동', 'outdoor', 2, '02-450-9311', NULL, 'futsal.or.kr', now()),
  ('futsal', '고척스카이돔풋살구장', '서울시', 'seoul_metro', '구로구 고척동', 'outdoor', 2, '02-120', NULL, 'futsal.or.kr', now()),
  ('futsal', '카미노풋살아레나', '서울시', 'seoul_metro', '금천구 남부순환로 1372 현경빌딩', 'indoor', 1, '010-2210-0214', NULL, 'futsal.or.kr', now()),
  ('futsal', '광운전자공업고등학교풋살장', '서울시', 'seoul_metro', '노원구 광운로 1길 24', 'outdoor', 1, '02-918-7761', NULL, 'futsal.or.kr', now()),
  ('futsal', '한국성서대학교풋살장', '서울시', 'seoul_metro', '노원구 동일로 214길 32', 'outdoor', 1, '02-950-5401', NULL, 'futsal.or.kr', now()),
  ('futsal', '온곡초등학교풋살장', '서울시', 'seoul_metro', '노원구 한글비석로 52길 59', 'outdoor', 1, '02-937-7136', NULL, 'futsal.or.kr', now()),
  ('futsal', '라온풋살장', '서울시', 'seoul_metro', '도봉구 방학동 553-2', 'outdoor', 1, '010-5041-0627', NULL, 'futsal.or.kr', now()),
  ('futsal', '신동아풋살클럽', '서울시', 'seoul_metro', '도봉구 방학로 223', 'outdoor', 1, '010-8608-8728', NULL, 'futsal.or.kr', now()),
  ('futsal', '초안산근린공원풋살장', '서울시', 'seoul_metro', '도봉구 창동', 'outdoor', 1, '02-2289-6855', NULL, 'futsal.or.kr', now()),
  ('futsal', '서울월드컵경기장풋살구장', '서울시', 'seoul_metro', '마포구 성산동', 'outdoor', 1, '02-2128-2973', NULL, 'futsal.or.kr', now()),
  ('futsal', '망원 유수지체육공원 풋살장', '서울시', 'seoul_metro', '마포구 월드컵로25길 190', 'outdoor', 1, '02-337-7319', NULL, 'futsal.or.kr', now()),
  ('futsal', '신북초등학교풋살장', '서울시', 'seoul_metro', '마포구 월드컵북로 38길 26', 'outdoor', 1, '02-303-6884', NULL, 'futsal.or.kr', now()),
  ('futsal', '로꼬풋살-서대문구 신촌로', '서울시', 'seoul_metro', '서대문구 신촌로 13', 'indoor', 1, '02-7747-6080', NULL, 'futsal.or.kr', now()),
  ('futsal', '서연중학교풋살장', '서울시', 'seoul_metro', '서대문구 연희동', 'outdoor', 1, '02-981-8279', NULL, 'futsal.or.kr', now()),
  ('futsal', '방배배수지체육공원', '서울시', 'seoul_metro', '서초구 남부순환로296길 4-9', 'outdoor', 1, '02-2155-6212', NULL, 'futsal.or.kr', now()),
  ('futsal', '반포종합운동장', '서울시', 'seoul_metro', '서초구 신반포로 16길 30', 'outdoor', 1, '02-2155-6212', NULL, 'futsal.or.kr', now()),
  ('futsal', '잠원스포츠파크풋살장', '서울시', 'seoul_metro', '서초구 잠원동', 'outdoor', 1, '02-533-7508', NULL, 'futsal.or.kr', now()),
  ('futsal', '케이지풋살파크', '서울시', 'seoul_metro', '서초구 효령로 36', 'indoor', 1, '010-8484-4424', NULL, 'futsal.or.kr', now()),
  ('futsal', '서울숲풋살장', '서울시', 'seoul_metro', '성동구 성수동 1가', 'outdoor', 1, '02-460-2905', NULL, 'futsal.or.kr', now()),
  ('futsal', '성수실내축구장by리팍', '서울시', 'seoul_metro', '성동구 성수이로 69', 'indoor', 1, '010-5955-6454', NULL, 'futsal.or.kr', now()),
  ('futsal', '케이지풋살아레나 성신여대점', '서울시', 'seoul_metro', '성북구 아리랑로4길 22 지하 1층', 'indoor', 1, '010-2210-0214', NULL, 'futsal.or.kr', now()),
  ('futsal', '성북종합레포츠타운', '서울시', 'seoul_metro', '성북구 한천로 58길 307', 'outdoor', 2, '070-8644-8275', NULL, 'futsal.or.kr', now()),
  ('futsal', '천마 풋살클럽', '서울시', 'seoul_metro', '송파구 마천동 68-21', 'outdoor', 3, '02-3401-5959', 'http://www.cmfutsalpark.com', 'futsal.or.kr', now()),
  ('futsal', '보인고등학교풋살장', '서울시', 'seoul_metro', '송파구 오금동 163', 'outdoor', 1, '02-2043-6021', NULL, 'futsal.or.kr', now()),
  ('futsal', '루프탑필드 목동점', '서울시', 'seoul_metro', '양천구 목동서로 170 홈플러스 6층', 'outdoor', 1, '02-6677-8776', NULL, 'futsal.or.kr', now()),
  ('futsal', '양동중학교풋살장', '서울시', 'seoul_metro', '양천구 목동중앙북로 49', 'outdoor', 1, '02-2642-8372', NULL, 'futsal.or.kr', now()),
  ('futsal', '로꼬풋살아레나 대림점', '서울시', 'seoul_metro', '영등포구 시흥대로 675', 'indoor', 1, '02-6080-7770', NULL, 'futsal.or.kr', now()),
  ('futsal', '영등포공원 풋살경기장', '서울시', 'seoul_metro', '영등포구 영등포동 582-6', 'outdoor', 1, '02-2670-3774', NULL, 'futsal.or.kr', now()),
  ('futsal', '오산고등학교풋살장', '서울시', 'seoul_metro', '용산구 보광로7길 17', 'outdoor', 1, '02-799-9537', NULL, 'futsal.or.kr', now()),
  ('futsal', '이촌한강공원풋살장', '서울시', 'seoul_metro', '용산구 한남동', 'outdoor', 1, '02-3780-0551', NULL, 'futsal.or.kr', now()),
  ('futsal', '영락중학교풋살장', '서울시', 'seoul_metro', '은평구 백련산로 134-6', 'outdoor', 1, '02-388-4033', NULL, 'futsal.or.kr', now()),
  ('futsal', '숭실중학교풋살장', '서울시', 'seoul_metro', '은평구 은평터널로 7길 6', 'outdoor', 1, '02-373-7641', NULL, 'futsal.or.kr', now()),
  ('futsal', '은평구립축구장', '서울시', 'seoul_metro', '은평구 진관동 242-6', 'outdoor', 1, '02-350-5393', NULL, 'futsal.or.kr', now()),
  ('futsal', '한양공업고등학교풋살장', '서울시', 'seoul_metro', '중구 을지로 299', 'outdoor', 1, '02-2238-5181', NULL, 'futsal.or.kr', now()),
  ('futsal', '로꼬아레나-동대문', '서울시', 'seoul_metro', '동대문구 답십리동 산2-9 힐스포파크 2층', 'indoor', 1, NULL, NULL, 'futsal.or.kr', now()),
  ('futsal', '성동FC풋살장', '서울시', 'seoul_metro', '성동구 고산자로 6길 40 2층', 'indoor', 1, NULL, NULL, 'futsal.or.kr', now()),
  ('futsal', '로꼬아레나-목동점', '서울시', 'seoul_metro', '양천구 목동 722-9 비바스포츠 5층', 'indoor', 2, NULL, NULL, 'futsal.or.kr', now()),
  ('futsal', '노원R 풋살장', '서울시', 'seoul_metro', '노원구 한글비석로 326 4층', 'indoor', 1, NULL, NULL, 'futsal.or.kr', now()),
  ('futsal', 'JS아카데미풋살장', '서울시', 'seoul_metro', '동대문구 휘경동 42-23 js빌딩 8층', 'indoor', 1, NULL, NULL, 'futsal.or.kr', now()),
  ('futsal', 'KSU실내풋살장', '서울시', 'seoul_metro', '양천구 은행정로 4길 16 2층', 'indoor', 2, NULL, NULL, 'futsal.or.kr', now()),
  ('futsal', '로꼬아레나-신도림', '서울시', 'seoul_metro', '구로구 신도림동 395-3 지하', 'indoor', 2, NULL, NULL, 'futsal.or.kr', now()),
  ('futsal', 'FC포텐셜-역삼', '서울시', 'seoul_metro', '강남구 역삼동 789-4 지하1층', 'indoor', 1, NULL, NULL, 'futsal.or.kr', now()),
  ('futsal', '스카이필드은평(롯데몰)', '서울시', 'seoul_metro', '은평구 진관동 79-15 롯데몰 은평점 9층', 'mixed', 4, NULL, NULL, 'futsal.or.kr', now()),
  ('futsal', '반세르풋살장', '서울시', 'seoul_metro', '강남구 역삼동 637-31 지하1층', 'indoor', 1, NULL, NULL, 'futsal.or.kr', now()),
  ('futsal', '스카이스포츠클럽(구의)', '서울시', 'seoul_metro', '광진구 구의동 223-65 옥상층', 'outdoor', 1, NULL, NULL, 'futsal.or.kr', now()),
  ('futsal', '서울이랜드FC(문정)', '서울시', 'seoul_metro', '송파구 문정동 97 B1층', 'indoor', 1, NULL, NULL, 'futsal.or.kr', now()),
  ('futsal', '노원하라풋살구장', '서울시', 'seoul_metro', '노원구 상계동 764-1', 'outdoor', 2, NULL, NULL, 'futsal.or.kr', now()),
  ('futsal', '로꼬풋살아레나 홍대점', '서울시', 'seoul_metro', '서대문구 창천동 506-20 4층', 'indoor', 2, NULL, NULL, 'futsal.or.kr', now()),
  ('futsal', '마곡이노풋살필드', '서울시', 'seoul_metro', '강서구 마곡동 800-1 4층', 'indoor', 1, NULL, NULL, 'futsal.or.kr', now()),
  ('futsal', 'GA실내풋살장', '서울시', 'seoul_metro', '관악구 봉천동 940-11', 'indoor', 1, NULL, NULL, 'futsal.or.kr', now()),
  ('futsal', '골든에이지풋살장', '서울시', 'seoul_metro', '중랑구 망우동 470-11 지하1층', 'indoor', 1, NULL, NULL, 'futsal.or.kr', now()),
  ('futsal', '목동유소년축구클럽풋살장', '서울시', 'seoul_metro', '강서구 양천구 신정동 296-1 새마을금고 4층', 'indoor', 1, NULL, NULL, 'futsal.or.kr', now()),
  ('futsal', '부산실내풋살장', '부산시', 'busan_ulsan_gn', '강서구 맥도강변길 207-1', 'indoor', NULL, '010-2056-1283', NULL, 'futsal.or.kr', now()),
  ('futsal', '풋볼스트리트', '부산시', 'busan_ulsan_gn', '금정구 금샘로 421 지하1층', 'indoor', NULL, '051-583-3026', NULL, 'futsal.or.kr', now()),
  ('futsal', '스포원파크풋살장', '부산시', 'busan_ulsan_gn', '금정구 두구동', 'outdoor', 4, '1577-0880', NULL, 'futsal.or.kr', now()),
  ('futsal', '기장풋살클럽', '부산시', 'busan_ulsan_gn', '기장군 일광면 삼성리', 'outdoor', NULL, NULL, NULL, 'futsal.or.kr', now()),
  ('futsal', '기장군월드컵빌리지 풋살장', '부산시', 'busan_ulsan_gn', '기장군 기장국민체육공원', 'outdoor', 1, '051-792-4780', NULL, 'futsal.or.kr', now()),
  ('futsal', '정관 일루션풋살장', '부산시', 'busan_ulsan_gn', '기장군 정관읍 용수공단2길 19-22', 'outdoor', NULL, '010-8510-3842', NULL, 'futsal.or.kr', now()),
  ('futsal', '정관FCN풋살장', '부산시', 'busan_ulsan_gn', '기장군 정관읍 정관로 266', 'outdoor', NULL, '010-7591-2002', NULL, 'futsal.or.kr', now()),
  ('futsal', '백운포공원풋살장', '부산시', 'busan_ulsan_gn', '남구 용호동', 'outdoor', 2, '051-607-6365', NULL, 'futsal.or.kr', now()),
  ('futsal', '부산풋살센터', '부산시', 'busan_ulsan_gn', '남구 우암동 114', 'outdoor', 3, '051-633-8479', NULL, 'futsal.or.kr', now()),
  ('futsal', '화명생태공원풋살장,축구장', '부산시', 'busan_ulsan_gn', '북구 화명동', 'outdoor', 3, '051-364-4127', NULL, 'futsal.or.kr', now()),
  ('futsal', '을숙도축구장', '부산시', 'busan_ulsan_gn', '사하구 낙동대로 398번길 12', 'outdoor', 2, '51-220-4838', NULL, 'futsal.or.kr', now()),
  ('futsal', '다대풋살센터', '부산시', 'busan_ulsan_gn', '사하구 다대로 544 진요빌딩 5층', 'outdoor', NULL, '051-294-1977', NULL, 'futsal.or.kr', now()),
  ('futsal', '영도마린축구장', '부산시', 'busan_ulsan_gn', '영도구 태종로 423', 'outdoor', NULL, '051-419-4852', NULL, 'futsal.or.kr', now()),
  ('futsal', '해운대카파풋살구장', '부산시', 'busan_ulsan_gn', '해운대구 우1동 산15-1', 'outdoor', 3, '010-3550-2675', NULL, 'futsal.or.kr', now()),
  ('futsal', '플레이짐풋살센터', '부산시', 'busan_ulsan_gn', '해운대구 좌동순환로 249번길 21', 'outdoor', NULL, '051-743-3360', NULL, 'futsal.or.kr', now()),
  ('futsal', 'PnC실내풋살장', '대구시', 'daegu_gb', '달서구 상화북로 189 신동빌딩 4층', 'indoor', NULL, '010-2345-0786', NULL, 'futsal.or.kr', now()),
  ('futsal', '달성실내풋살장', '대구시', 'daegu_gb', '달성군 옥포면 비슬로 431길 19', 'indoor', NULL, '053-264-0827', NULL, 'futsal.or.kr', now()),
  ('futsal', '빅매치', '대구시', 'daegu_gb', '동구 대경로 15', 'outdoor', NULL, '070-8886-9475', NULL, 'futsal.or.kr', now()),
  ('futsal', '반야월풋살장', '대구시', 'daegu_gb', '동구 안심로 69길 23', 'outdoor', 1, '010-2548-1110', NULL, 'futsal.or.kr', now()),
  ('futsal', '대구시민안전테마파크풋살장', '대구시', 'daegu_gb', '동구 용수동', 'outdoor', 1, '053-980-7777', NULL, 'futsal.or.kr', now()),
  ('futsal', 'K&P스포츠복현풋살클럽', '대구시', 'daegu_gb', '북구 검단로 16', 'outdoor', NULL, '053-383-2630', NULL, 'futsal.or.kr', now()),
  ('futsal', '강북웰빙랜드', '대구시', 'daegu_gb', '북구 구리로 29', 'outdoor', 1, '053-314-3333', NULL, 'futsal.or.kr', now()),
  ('futsal', '복현풋살클럽', '대구시', 'daegu_gb', '북구 복현로8길 16-58', 'outdoor', 1, '053-959-8700', NULL, 'futsal.or.kr', now()),
  ('futsal', 'J풋살파크', '대구시', 'daegu_gb', '북구 유통단지로 60 텍스빌 혼수백화점 4층', 'outdoor', NULL, '053-601-0505', NULL, 'futsal.or.kr', now()),
  ('futsal', '강북풋살장', '대구시', 'daegu_gb', '북구 읍내동', 'outdoor', NULL, NULL, NULL, 'futsal.or.kr', now()),
  ('futsal', '하이두 축구클럽하이두 풋살장', '대구시', 'daegu_gb', '북구 학정로 92', 'outdoor', NULL, '053-314-0050', NULL, 'futsal.or.kr', now()),
  ('futsal', '팔공풋살구장', '대구시', 'daegu_gb', '북구 호국로 804', 'outdoor', 4, '053-764-7484', NULL, 'futsal.or.kr', now()),
  ('futsal', 'JS풋살구장', '대구시', 'daegu_gb', '수성구 지범로23길 20', 'outdoor', NULL, '010-2913-2502', NULL, 'futsal.or.kr', now()),
  ('futsal', '대구풋살', '대구시', 'daegu_gb', '수성구 시지동 238', 'outdoor', 6, '053-795-7950', NULL, 'futsal.or.kr', now()),
  ('futsal', '쿠풋살센터', '인천시', 'seoul_metro', '계양구 아나지로 494', 'indoor', NULL, '010-7394-5755', NULL, 'futsal.or.kr', now()),
  ('futsal', '스토래지인천남동점', '인천시', 'seoul_metro', '남동구 경신로 56', 'indoor', NULL, '032-462-0513', NULL, 'futsal.or.kr', now()),
  ('futsal', '로꼬풋살', '인천시', 'seoul_metro', '남동구 예술로 148 롯데백화점 10층', 'outdoor', NULL, '032-450-2928', NULL, 'futsal.or.kr', now()),
  ('futsal', '인천대공원풋살장', '인천시', 'seoul_metro', '남동구 장수동', 'outdoor', 1, '032-466-7282', NULL, 'futsal.or.kr', now()),
  ('futsal', '만석어린이공원풋살구장', '인천시', 'seoul_metro', '동구 만석동', 'outdoor', NULL, NULL, NULL, 'futsal.or.kr', now()),
  ('futsal', '케이지풋살아레나부평', '인천시', 'seoul_metro', '부평구 장제로 159번길 4', 'indoor', NULL, '010-5142-3345', NULL, 'futsal.or.kr', now()),
  ('futsal', '신석체육공원풋살장', '인천시', 'seoul_metro', '서구 석남동', 'outdoor', 1, '032-573-6727', NULL, 'futsal.or.kr', now()),
  ('futsal', '드림파크풋살장', '인천시', 'seoul_metro', '서구 오류동', 'outdoor', NULL, NULL, NULL, 'futsal.or.kr', now()),
  ('futsal', '청라북항 풋살장', '인천시', 'seoul_metro', '서구 원창동 381-76', 'outdoor', NULL, '010-4576-1633', NULL, 'futsal.or.kr', now()),
  ('futsal', '플레이풋살', '인천시', 'seoul_metro', '연수구 송도과학로 16번길 33-3', 'outdoor', NULL, '010-9215-1177', NULL, 'futsal.or.kr', now()),
  ('futsal', '동춘풋살파크', '인천시', 'seoul_metro', '연수구 앵고개로 266', 'outdoor', 1, '010-9028-0990', NULL, 'futsal.or.kr', now()),
  ('futsal', '송도 LNG 종합스포츠 타운', '인천시', 'seoul_metro', '연수구 인천신항대로 916', 'outdoor', 2, NULL, NULL, 'futsal.or.kr', now()),
  ('futsal', '인천유나이티드 팩토리 풋살파크', '인천시', 'seoul_metro', '중구 서해대로 209번길 2', 'indoor', NULL, '032-728-2850', NULL, 'futsal.or.kr', now()),
  ('futsal', '중구국민체육센터 풋살장', '인천시', 'seoul_metro', '중구 신흥동 3가', 'indoor', NULL, '032-763-8270', NULL, 'futsal.or.kr', now()),
  ('futsal', '금강풋살', '대전시', 'chungcheong', '대덕구 대덕대로 1575', 'outdoor', NULL, '042-933-8455', NULL, 'futsal.or.kr', now()),
  ('futsal', '덕암축구센터', '대전시', 'chungcheong', '대덕구 목상동 250-4', 'outdoor', NULL, '042-933-2972', NULL, 'futsal.or.kr', now()),
  ('futsal', '스페인국제축구클럽', '대전시', 'chungcheong', '대덕구 방두말5길 2', 'outdoor', NULL, '010-9223-0339', NULL, 'futsal.or.kr', now()),
  ('futsal', '송촌생활체육공원풋살경기장', '대전시', 'chungcheong', '대덕구 법동', 'outdoor', 1, '042-933-8890', NULL, 'futsal.or.kr', now()),
  ('futsal', '지수생활체육공원 풋살장', '대전시', 'chungcheong', '대덕구 산업단지로 93번길 101', 'outdoor', 4, '042-933-2974', NULL, 'futsal.or.kr', now()),
  ('futsal', '대전판암풋살', '대전시', 'chungcheong', '동구 동부로 43', 'outdoor', NULL, '042-283-0505', NULL, 'futsal.or.kr', now()),
  ('futsal', 'HM풋살파크동대전점 & Hi5축구클럽', '대전시', 'chungcheong', '동구 한밭대로 1282', 'outdoor', NULL, '042-636-0885', NULL, 'futsal.or.kr', now()),
  ('futsal', '월평풋살', '대전시', 'chungcheong', '서구 갑천도시고속도로 1959', 'outdoor', 3, '042-488-5593', NULL, 'futsal.or.kr', now()),
  ('futsal', '도안숲공원풋살경기장', '대전시', 'chungcheong', '서구 도안동', 'outdoor', NULL, '010-5427-3999', NULL, 'futsal.or.kr', now()),
  ('futsal', '강남풋살편의점', '대전시', 'chungcheong', '서구 월평 1동 82-4', 'outdoor', 5, '042-861-7045', NULL, 'futsal.or.kr', now()),
  ('futsal', '송강풋살구장', '대전시', 'chungcheong', '유성구 금남구즉로 1423', 'outdoor', NULL, '042-935-7733', NULL, 'futsal.or.kr', now()),
  ('futsal', '굿모닝풋살구장', '대전시', 'chungcheong', '유성구 노은로 367번길 108', 'outdoor', NULL, '010-7171-7044', NULL, 'futsal.or.kr', now()),
  ('futsal', '대전스카이풋살파크', '대전시', 'chungcheong', '유성구 대정북로 2', 'outdoor', NULL, '010-5130-5474', NULL, 'futsal.or.kr', now()),
  ('futsal', '케이지풋살아레나 충남대점', '대전시', 'chungcheong', '유성구 유성대로 798-1', 'indoor', NULL, '010-4422-8407', NULL, 'futsal.or.kr', now()),
  ('futsal', '유성강변풋살장', '대전시', 'chungcheong', '유성구 봉명동 611-5', 'outdoor', 2, '042-825-5399', NULL, 'futsal.or.kr', now()),
  ('futsal', '한밭풋살구장', '대전시', 'chungcheong', '유성구 현충원로 364', 'outdoor', 4, '010-2841-8484', NULL, 'futsal.or.kr', now()),
  ('futsal', '경성풋살구장', '대전시', 'chungcheong', '중구 경성풋살구장', 'mixed', NULL, '042-538-7012', NULL, 'futsal.or.kr', now()),
  ('futsal', '신가풋살', '광주시', 'gwangju', '광산구 목련로 382번안길 48', 'outdoor', 1, '010-4499-1233', NULL, 'futsal.or.kr', now()),
  ('futsal', '광산FC풋살장', '광주시', 'gwangju', '광산구 사암로 860-25', 'outdoor', NULL, NULL, NULL, 'futsal.or.kr', now()),
  ('futsal', '신화스포디움', '광주시', 'gwangju', '광산구 왕버들로 33', 'mixed', NULL, '010-8621-0809', NULL, 'futsal.or.kr', now()),
  ('futsal', '베스트 풋살', '광주시', 'gwangju', '광산구 풍영정길 241-9', 'outdoor', NULL, '010-6594-0500', NULL, 'futsal.or.kr', now()),
  ('futsal', '제일풋살장-운남동', '광주시', 'gwangju', '광산구 풍영철길로 188-5', 'outdoor', NULL, '010-2212-6861', NULL, 'futsal.or.kr', now()),
  ('futsal', '태양풋살', '광주시', 'gwangju', '광산구 하남대로 9', 'outdoor', NULL, '010-9675-1233', NULL, 'futsal.or.kr', now()),
  ('futsal', '케이지풋살아레나 백운점', '광주시', 'gwangju', '남구 독립로 106 지하 1층', 'indoor', NULL, '010-3309-3696', NULL, 'futsal.or.kr', now()),
  ('futsal', 'JK풋살아레나', '광주시', 'gwangju', '북구 양일로 60', 'indoor', NULL, '062-573-0829', NULL, 'futsal.or.kr', now()),
  ('futsal', '히딩크드림필드광주구장', '광주시', 'gwangju', '서구 덕흥동', 'outdoor', NULL, NULL, NULL, 'futsal.or.kr', now()),
  ('futsal', '상무풋살', '광주시', 'gwangju', '서구 유덕로 45', 'outdoor', 3, '010-8612-3185', NULL, 'futsal.or.kr', now()),
  ('futsal', '케이지풋살아레나 백운점', '광주시', 'gwangju', '북구 반룡로 42번길 11', 'indoor', NULL, '010-3309-3696', NULL, 'futsal.or.kr', now()),
  ('futsal', '삼호풋살경기장', '울산시', 'busan_ulsan_gn', '남구 무거동', 'outdoor', 1, NULL, NULL, 'futsal.or.kr', now()),
  ('futsal', '코운스아카데미스포츠', '울산시', 'busan_ulsan_gn', '남구 봉월로 15', 'indoor', NULL, '052-258-0353', NULL, 'futsal.or.kr', now()),
  ('futsal', 'HM풋살파크울산남구점', '울산시', 'busan_ulsan_gn', '남구 수암로 148 홈플러스', 'outdoor', 1, '052-227-1380', NULL, 'futsal.or.kr', now()),
  ('futsal', '울산대공원풋살경기장', '울산시', 'busan_ulsan_gn', '남구 옥동', 'outdoor', 2, '052-271-8818', NULL, 'futsal.or.kr', now()),
  ('futsal', '문수월드컵경기장풋살경기장', '울산시', 'busan_ulsan_gn', '남구 옥동', 'outdoor', 2, '052-220-2002', NULL, 'futsal.or.kr', now()),
  ('futsal', '필그린풋살클럽', '울산시', 'busan_ulsan_gn', '남구 화합로 81', 'outdoor', NULL, '010-8933-8310', NULL, 'futsal.or.kr', now()),
  ('futsal', '일산천풋살경기장', '울산시', 'busan_ulsan_gn', '동구 일산동 443', 'outdoor', 1, '052-209-3338', NULL, 'futsal.or.kr', now()),
  ('futsal', '히딩크드림필드', '울산시', 'busan_ulsan_gn', '동구 전하동 140-2', 'unknown', NULL, '052-209-3316', NULL, 'futsal.or.kr', now()),
  ('futsal', '일산풋살클럽', '울산시', 'busan_ulsan_gn', '동구 해수욕장 4길 18', 'outdoor', NULL, '052-235-5797', NULL, 'futsal.or.kr', now()),
  ('futsal', '간절곶스포츠파크풋살경기', '울산시', 'busan_ulsan_gn', '울주군 서생면 서생리', 'outdoor', 1, '052-229-9800', NULL, 'futsal.or.kr', now()),
  ('futsal', '울산종합운동장풋살장', '울산시', 'busan_ulsan_gn', '중구 남외동', 'outdoor', NULL, '052-294-4120', NULL, 'futsal.or.kr', now()),
  ('futsal', '태화강체육공원풋살장', '울산시', 'busan_ulsan_gn', '중구 성남동', 'outdoor', 1, '052-229-9800', NULL, 'futsal.or.kr', now()),
  ('futsal', '고양풋살센터', '경기도', 'seoul_metro', '고양시 덕양구 흥도로 78', 'mixed', 3, '031-970-2246', NULL, 'futsal.or.kr', now()),
  ('futsal', '팬텀 실내 풋살장', '경기도', 'seoul_metro', '고양시 일산동구 고봉로 658번길 61-36', 'indoor', 2, '010-5691-1075', NULL, 'futsal.or.kr', now()),
  ('futsal', '킹실내풋살센터', '경기도', 'seoul_metro', '고양시 일산동구 고양대로 1074-7', 'indoor', NULL, '010-2227-2828', NULL, 'futsal.or.kr', now()),
  ('futsal', 'H풋볼클럽', '경기도', 'seoul_metro', '구리시 검배로 176-58', 'indoor', NULL, '010-9912-1818', NULL, 'futsal.or.kr', now()),
  ('futsal', '다원풋살장', '경기도', 'seoul_metro', '남양주시 경춘로 953', 'outdoor', 1, '070-8709-4862', NULL, 'futsal.or.kr', now()),
  ('futsal', '김병지축구교실별내풋살장', '경기도', 'seoul_metro', '남양주시 두물로 27번길 37', 'outdoor', 1, '1644-7552', NULL, 'futsal.or.kr', now()),
  ('futsal', 'HMFUTSALPARK 부천중동점', '경기도', 'seoul_metro', '부천시 길주로 297', 'outdoor', NULL, '070-4408-7732', NULL, 'futsal.or.kr', now()),
  ('futsal', '옥상달빛풋살장', '경기도', 'seoul_metro', '성남시 수정구 수정로 115-1', 'outdoor', 1, '070-4949-3561', NULL, 'futsal.or.kr', now()),
  ('futsal', '팩토리풋살파크', '경기도', 'seoul_metro', '수원시 권선구 수인로 163-1', 'outdoor', NULL, '070-8263-0390', NULL, 'futsal.or.kr', now()),
  ('futsal', '박지성축구센터풋살파크', '경기도', 'seoul_metro', '수원시 영통구 반정로 216', 'unknown', NULL, NULL, NULL, 'futsal.or.kr', now()),
  ('futsal', '에스빌드 풋살파크', '경기도', 'seoul_metro', '수원시 팔달구 월드컵로 310', 'outdoor', NULL, '1577-4228', NULL, 'futsal.or.kr', now()),
  ('futsal', '케이지블루풋살존', '경기도', 'seoul_metro', '수원시 팔달구 인계로 108번길 39-17', 'indoor', NULL, '031-233-9363', NULL, 'futsal.or.kr', now()),
  ('futsal', '드림풋살구장', '경기도', 'seoul_metro', '시흥시 수인로 2602', 'outdoor', 2, '010-4183-0351', NULL, 'futsal.or.kr', now()),
  ('futsal', '케이지풋살아레나시흥점', '경기도', 'seoul_metro', '시흥시 시흥대로 1074번길 5', 'indoor', NULL, '070-7760-0643', NULL, 'futsal.or.kr', now()),
  ('futsal', '씨엘스포츠', '경기도', 'seoul_metro', '안산시 단원구 선부광장로 23', 'outdoor', NULL, '010-3070-0639', NULL, 'futsal.or.kr', now()),
  ('futsal', '덕봉아레나', '경기도', 'seoul_metro', '안성시 양성면 덕봉길 90-11', 'indoor', NULL, '010-5119-8730', NULL, 'futsal.or.kr', now()),
  ('futsal', '안양MASTER풋살파크', '경기도', 'seoul_metro', '안양시 동안구 평촌대로 386', 'indoor', 1, NULL, NULL, 'futsal.or.kr', now()),
  ('futsal', '양주풋살파크', '경기도', 'seoul_metro', '양주시 마전로 118번길 183', 'mixed', NULL, '031-840-5335', NULL, 'futsal.or.kr', now()),
  ('futsal', '송산배수지체육시설풋살장', '경기도', 'seoul_metro', '의정부시 신곡동', 'outdoor', 1, NULL, NULL, 'futsal.or.kr', now()),
  ('futsal', '파워실내스포츠', '경기도', 'seoul_metro', '의정부시 체육로 229', 'indoor', NULL, '031-875-1539', NULL, 'futsal.or.kr', now()),
  ('futsal', '교하풋살장', '경기도', 'seoul_metro', '파주시 교하로 1414-13', 'outdoor', 1, '010-9303-7472', NULL, 'futsal.or.kr', now()),
  ('futsal', '스포츠몬스터풋살파크', '경기도', 'seoul_metro', '하남시 미사대로 750 스타필드', 'outdoor', NULL, '031-8072-8895', NULL, 'futsal.or.kr', now()),
  ('futsal', 'FCBD봉담유소년축구클럽', '경기도', 'seoul_metro', '화성시 봉담읍 동화리 245-12', 'outdoor', NULL, '031-298-6546', NULL, 'futsal.or.kr', now()),
  ('futsal', '교동택지풋살장-강릉', '강원도', 'gangwon', '강릉시 교동', 'outdoor', NULL, '033-647-2004', NULL, 'futsal.or.kr', now()),
  ('futsal', '고성군공설운동장 풋살장', '강원도', 'gangwon', '고성군 간성읍 상리', 'outdoor', 2, '033-680-3711', NULL, 'futsal.or.kr', now()),
  ('futsal', '동해웰빙레포츠타운 풋살장', '강원도', 'gangwon', '동해시 덕골길 10', 'outdoor', NULL, '033-539-8184', NULL, 'futsal.or.kr', now()),
  ('futsal', '속초시공설운동장풋살장', '강원도', 'gangwon', '속초시 노학동', 'outdoor', 1, '033-639-2474', NULL, 'futsal.or.kr', now()),
  ('futsal', '양양종합운동장풋살장', '강원도', 'gangwon', '양양군 양양읍 구교리', 'outdoor', NULL, '033-670-2254', NULL, 'futsal.or.kr', now()),
  ('futsal', '영월스포츠파크 풋살장', '강원도', 'gangwon', '영월군 영월읍 하송리', 'outdoor', NULL, '033-370-2089', NULL, 'futsal.or.kr', now()),
  ('futsal', 'SMC 풋살구장-원주', '강원도', 'gangwon', '원주시 흥업면 북원로 1800', 'outdoor', NULL, '010-8799-9635', NULL, 'futsal.or.kr', now()),
  ('futsal', '원통생활체육공원풋살장', '강원도', 'gangwon', '인제군 북면 원통리', 'outdoor', NULL, '1588-2201', NULL, 'futsal.or.kr', now()),
  ('futsal', '사북생활체육공원풋살장', '강원도', 'gangwon', '정선군 사북읍', 'outdoor', 2, '033-560-2547', NULL, 'futsal.or.kr', now()),
  ('futsal', '공지천유원지풋살장', '강원도', 'gangwon', '춘천시 근화동', 'outdoor', NULL, '033-250-3089', NULL, 'futsal.or.kr', now()),
  ('futsal', '춘천송암레포츠타운 풋살장', '강원도', 'gangwon', '춘천시 송암동', 'outdoor', NULL, '033-264-0660', NULL, 'futsal.or.kr', now()),
  ('futsal', '태백종합운동장풋살경기장', '강원도', 'gangwon', '태백시 문곡동', 'outdoor', NULL, '033-560-2547', NULL, 'futsal.or.kr', now()),
  ('futsal', '홍천군 풋살경기장', '강원도', 'gangwon', '홍천군', 'outdoor', NULL, '033-436-7330', NULL, 'futsal.or.kr', now()),
  ('futsal', '횡성실내체육관', '강원도', 'gangwon', '횡성군 횡성읍 문화체육로 57', 'indoor', NULL, '033-340-5951', NULL, 'futsal.or.kr', now()),
  ('futsal', '횡성종합운동장풋살경기장', '강원도', 'gangwon', '횡성군 횡성읍 북천리', 'outdoor', 2, '033-340-5951', NULL, 'futsal.or.kr', now()),
  ('futsal', '하소생활체육공원풋살장', '충청북도', 'chungcheong', '제천시 하소동', 'outdoor', 1, '043-641-5598', NULL, 'futsal.or.kr', now()),
  ('futsal', '진천선수촌풋살장', '충청북도', 'chungcheong', '진천군 광혜원면 선수촌로 105', 'outdoor', 1, '043-531-0114', NULL, 'futsal.or.kr', now()),
  ('futsal', '용정축구공원', '충청북도', 'chungcheong', '청주시 상당구 1순환로 1594번길 42', 'outdoor', 1, '043-270-8568', NULL, 'futsal.or.kr', now()),
  ('futsal', '월드컵풋살장', '충청북도', 'chungcheong', '청주시 서원구 남이면 가마길 57', 'outdoor', NULL, '043-294-2002', NULL, 'futsal.or.kr', now()),
  ('futsal', '국제풋살', '충청북도', 'chungcheong', '청주시 서원구 남이면 가좌리', 'outdoor', 3, '043-254-5005', NULL, 'futsal.or.kr', now()),
  ('futsal', '위너스실내풋살', '충청북도', 'chungcheong', '청주시 서원구 내수동로 108번길 51', 'indoor', NULL, '043-266-5855', NULL, 'futsal.or.kr', now()),
  ('futsal', '탑스포츠아카데미', '충청북도', 'chungcheong', '청주시 서원구 복대로 15 두성빌딩', 'indoor', NULL, '043-234-2201', NULL, 'futsal.or.kr', now()),
  ('futsal', '현도실내풋살구장', '충청북도', 'chungcheong', '청주시 서원구 현도면 시목외천로 146', 'indoor', 2, '043-264-7700', NULL, 'futsal.or.kr', now()),
  ('futsal', 'A7 실내풋살장', '충청북도', 'chungcheong', '청주시 청원구 새터로 176번길 23', 'indoor', NULL, '010-3409-0302', NULL, 'futsal.or.kr', now()),
  ('futsal', '오창풋살클럽', '충청북도', 'chungcheong', '청주시 청원구 오창읍 구룡택지1로 87-74', 'outdoor', 2, '043-217-5698', NULL, 'futsal.or.kr', now()),
  ('futsal', '직지풋살', '충청북도', 'chungcheong', '청주시 청원구 충청대로 320', 'outdoor', 3, '043-213-7749', NULL, 'futsal.or.kr', now()),
  ('futsal', '충청풋살체육공원', '충청북도', 'chungcheong', '청주시 흥덕구 강내면 석화리 256', 'outdoor', 4, '043-269-0801', NULL, 'futsal.or.kr', now()),
  ('futsal', '충북풋살구장', '충청북도', 'chungcheong', '청주시 흥덕구 신봉동 234-3', 'indoor', 2, '043-277-0079', NULL, 'futsal.or.kr', now()),
  ('futsal', '청주풋살클럽', '충청북도', 'chungcheong', '청주시 흥덕구 월명로 252번길 44', 'outdoor', 2, '043-266-5112', NULL, 'futsal.or.kr', now()),
  ('futsal', '충주풋살장', '충청북도', 'chungcheong', '충주시 칠금동 445-54', 'indoor', NULL, '010-8836-3511', NULL, 'futsal.or.kr', now()),
  ('futsal', '금산풋살', '충청남도', 'chungcheong', '금산군 금산읍 원줄길 32', 'indoor', NULL, '041-753-5144', NULL, 'futsal.or.kr', now()),
  ('futsal', '논산풋살축구클럽', '충청남도', 'chungcheong', '논산시 채운면 채운로36번길 33-25', 'outdoor', 4, '041-734-5266', NULL, 'futsal.or.kr', now()),
  ('futsal', '원당풋살경기장', '충청남도', 'chungcheong', '당진시 원당동 461-8', 'outdoor', 2, '010-4083-1410', NULL, 'futsal.or.kr', now()),
  ('futsal', '보령풋살장', '충청남도', 'chungcheong', '보령시 신흑동', 'outdoor', 1, NULL, NULL, 'futsal.or.kr', now()),
  ('futsal', '서산실내풋살장', '충청남도', 'chungcheong', '서산시 서령로 74', 'indoor', NULL, '070-5033-6663', NULL, 'futsal.or.kr', now()),
  ('futsal', '서산풋살축구센터', '충청남도', 'chungcheong', '서산시 안견로 718', 'outdoor', NULL, '010-3451-4597', NULL, 'futsal.or.kr', now()),
  ('futsal', '서천국민체육센터풋살장', '충청남도', 'chungcheong', '서천군 마서면 옥산리', 'outdoor', 2, '041-952-6457', NULL, 'futsal.or.kr', now()),
  ('futsal', '아산풋살장', '충청남도', 'chungcheong', '아산시 염치읍 아산로 658-41', 'indoor', NULL, '041-532-7751', NULL, 'futsal.or.kr', now()),
  ('futsal', '천안풋살', '충청남도', 'chungcheong', '천안시 동남구 가마골1길 12', 'outdoor', NULL, '010-6273-7330', NULL, 'futsal.or.kr', now()),
  ('futsal', '통정 풋살 파크', '충청남도', 'chungcheong', '천안시 동남구 신방동 1140', 'outdoor', NULL, '010-3426-6119', NULL, 'futsal.or.kr', now()),
  ('futsal', '으뜸풋살', '충청남도', 'chungcheong', '천안시 서북구 4산단7로 16-25', 'indoor', NULL, '041-582-8555', NULL, 'futsal.or.kr', now()),
  ('futsal', '퍼펙트스포츠센터', '충청남도', 'chungcheong', '천안시 서북구 쌍용 14길 70', 'outdoor', 2, '041-575-7757', NULL, 'futsal.or.kr', now()),
  ('futsal', '풋살존', '충청남도', 'chungcheong', '천안시 서북구 천안대로 1346-36', 'indoor', NULL, '010-6648-7750', NULL, 'futsal.or.kr', now()),
  ('futsal', '소룡동시민체육공원풋살장', '전라북도', 'jeonnam', '군산시 소룡동', 'outdoor', 2, NULL, NULL, 'futsal.or.kr', now()),
  ('futsal', '김제시민운동장풋살장', '전라북도', 'jeonnam', '김제시 검산동', 'outdoor', 2, '063-540-4095', NULL, 'futsal.or.kr', now()),
  ('futsal', '수도산체육공원풋살장', '전라북도', 'jeonnam', '익산시 금강동', 'outdoor', 1, '63-859-4618', NULL, 'futsal.or.kr', now()),
  ('futsal', '영등시민공원풋살장', '전라북도', 'jeonnam', '익산시 영등동', 'outdoor', 1, '063-859-4618', NULL, 'futsal.or.kr', now()),
  ('futsal', '중앙체육공원풋살장', '전라북도', 'jeonnam', '익산시 하나로 322 중앙체육공원', 'outdoor', 2, '063-859-4618', NULL, 'futsal.or.kr', now()),
  ('futsal', '챔피언스풋살파크', '전라북도', 'jeonnam', '전주시 덕진구 안덕원로 382', 'mixed', NULL, '010-5812-0240', NULL, 'futsal.or.kr', now()),
  ('futsal', 'A클래스 풋살클럽', '전라북도', 'jeonnam', '전주시 덕진구 오송로9 3', 'indoor', NULL, '010-2083-8179', NULL, 'futsal.or.kr', now()),
  ('futsal', '에이스풋살', '전라북도', 'jeonnam', '전주시 덕진구 추천로 211', 'outdoor', NULL, '063-277-8955', NULL, 'futsal.or.kr', now()),
  ('futsal', '조가케이지풋살장', '전라북도', 'jeonnam', '전주시 완산구 용머리로 36', 'indoor', NULL, '010-2251-4387', NULL, 'futsal.or.kr', now()),
  ('futsal', '풋살일번가', '전라북도', 'jeonnam', '전주시 완산구 유연로 327', 'indoor', NULL, '010-5882-0490', NULL, 'futsal.or.kr', now()),
  ('futsal', '황토현수련원풋살장', '전라북도', 'jeonnam', '정읍시 고부면 태고로 577', 'outdoor', 1, '063-532-8999', NULL, 'futsal.or.kr', now()),
  ('futsal', '드림실내풋살장-광양', '전라남도', 'jeonnam', '광양시 광양읍 매천로 776', 'indoor', NULL, '061-762-3350', NULL, 'futsal.or.kr', now()),
  ('futsal', '마동그린공원체육시설', '전라남도', 'jeonnam', '광양시 무등길 90', 'mixed', 2, '061-797-2413', NULL, 'futsal.or.kr', now()),
  ('futsal', '산정동생활체육공원풋살장', '전라남도', 'jeonnam', '목포시 산정동', 'outdoor', 1, NULL, NULL, 'futsal.or.kr', now()),
  ('futsal', '목포시청소년수련원풋살장', '전라남도', 'jeonnam', '목포시 양을로 397번길 68', 'outdoor', 1, '061-276-3640', NULL, 'futsal.or.kr', now()),
  ('futsal', '벌교생태공원축구장', '전라남도', 'jeonnam', '보성군 벌교읍 장양리 1431-11', 'outdoor', 1, '061-858-6900', NULL, 'futsal.or.kr', now()),
  ('futsal', '상사종합체육관풋살장', '전라남도', 'jeonnam', '순천시 상사면 응령리', 'outdoor', 3, NULL, NULL, 'futsal.or.kr', now()),
  ('futsal', '신대순천풋살구장', '전라남도', 'jeonnam', '순천시 해룡면 지봉로 123-1', 'outdoor', NULL, '061-727-6565', NULL, 'futsal.or.kr', now()),
  ('futsal', '선월풋살구장', '전라남도', 'jeonnam', '순천시 해룡면 호두구상길 136', 'outdoor', NULL, '061-726-7953', NULL, 'futsal.or.kr', now()),
  ('futsal', '여수풋살경기장', '전라남도', 'jeonnam', '여수시 여서동', 'outdoor', 3, '061-655-7979', NULL, 'futsal.or.kr', now()),
  ('futsal', '영광스포티움풋살장', '전라남도', 'jeonnam', '영광군 영광읍 단주리', 'outdoor', 1, '061-350-4852', NULL, 'futsal.or.kr', now()),
  ('futsal', '완도공설운동장 축구전용구장', '전라남도', 'jeonnam', '완도군 완도읍 가용리 50-31', 'outdoor', 1, '061-550-5487', NULL, 'futsal.or.kr', now()),
  ('futsal', '신천풋살장', '경상북도', 'daegu_gb', '경산시 강변동로 238', 'outdoor', NULL, '053-814-6511', NULL, 'futsal.or.kr', now()),
  ('futsal', 'J&F실내풋살클럽', '경상북도', 'daegu_gb', '경산시 인흥2길 2-50', 'indoor', NULL, '053-857-9113', NULL, 'futsal.or.kr', now()),
  ('futsal', '안심실내풋살장', '경상북도', 'daegu_gb', '경산시 하양읍 달바소길 95', 'indoor', NULL, '053-963-7272', NULL, 'futsal.or.kr', now()),
  ('futsal', 'FC리더스풋살경기장', '경상북도', 'daegu_gb', '경산시 하양읍 은호리', 'outdoor', 3, '053-857-6699', NULL, 'futsal.or.kr', now()),
  ('futsal', '용강풋살파크', '경상북도', 'daegu_gb', '경주시 다불로 108', 'outdoor', 3, '054-776-0925', NULL, 'futsal.or.kr', now()),
  ('futsal', '비바풋살클럽', '경상북도', 'daegu_gb', '구미시 고아읍 송평로 47', 'outdoor', 4, '054-457-7782', NULL, 'futsal.or.kr', now()),
  ('futsal', '구미스피드풋살클럽', '경상북도', 'daegu_gb', '구미시 봉곡남로 25길 31', 'outdoor', 3, '054-442-9494', NULL, 'futsal.or.kr', now()),
  ('futsal', '구미지산풋살', '경상북도', 'daegu_gb', '구미시 선산대로 19-11', 'outdoor', 4, '054-458-7800', NULL, 'futsal.or.kr', now()),
  ('futsal', '남구미풋살클럽', '경상북도', 'daegu_gb', '구미시 오태1길 9', 'outdoor', 4, '054-462-8484', NULL, 'futsal.or.kr', now()),
  ('futsal', '금오풋살클럽', '경상북도', 'daegu_gb', '구미시 화신로길 4', 'outdoor', 4, '054-456-8490', NULL, 'futsal.or.kr', now()),
  ('futsal', '김천풋살경기장', '경상북도', 'daegu_gb', '김천시 다수동 206-1', 'outdoor', 3, '054-430-1988', NULL, 'futsal.or.kr', now()),
  ('futsal', '문경새재도립공원풋살장', '경상북도', 'daegu_gb', '문경시 문경읍 상초리', 'outdoor', 1, '054-571-0709', NULL, 'futsal.or.kr', now()),
  ('futsal', '인사이드 케이지 풋살', '경상북도', 'daegu_gb', '안동시 육사로 325', 'unknown', NULL, '010-8985-6135', NULL, 'futsal.or.kr', now()),
  ('futsal', '왜관풋살경기장', '경상북도', 'daegu_gb', '칠곡군 왜관읍 왜관리 849-2', 'outdoor', 2, '054-973-4555', NULL, 'futsal.or.kr', now()),
  ('futsal', '우현풋살', '경상북도', 'daegu_gb', '포항시 북구 소티재로 154', 'outdoor', 3, '054-232-9977', NULL, 'futsal.or.kr', now()),
  ('futsal', '현대풋살파크', '경상북도', 'daegu_gb', '포항시 북구 장량로87번길 37', 'outdoor', 3, '054-255-2080', NULL, 'futsal.or.kr', now()),
  ('futsal', '흥해풋살', '경상북도', 'daegu_gb', '포항시 북구 흥해읍 동해대로 1523', 'outdoor', 2, '054-262-7811', NULL, 'futsal.or.kr', now()),
  ('futsal', '이동풋살', '경상북도', 'daegu_gb', '포항시 남구 대잠동', 'outdoor', 2, NULL, NULL, 'futsal.or.kr', now()),
  ('futsal', '거제풋살경기장', '경상남도', 'busan_ulsan_gn', '거제시 연초면 소오비1길 22', 'outdoor', NULL, '055-635-6255', NULL, 'futsal.or.kr', now()),
  ('futsal', '브라더풋살장', '경상남도', 'busan_ulsan_gn', '김해시 김해대로 2406', 'outdoor', NULL, '010-6629-1082', NULL, 'futsal.or.kr', now()),
  ('futsal', '대동실내풋살장', '경상남도', 'busan_ulsan_gn', '김해시 대동면 동남로 49번길 90-16', 'indoor', NULL, '055-322-2515', NULL, 'futsal.or.kr', now()),
  ('futsal', '그린힐풋살구장', '경상남도', 'busan_ulsan_gn', '김해시 삼계동 847-5', 'indoor', NULL, '055-334-6167', NULL, 'futsal.or.kr', now()),
  ('futsal', '삼계풋살구장', '경상남도', 'busan_ulsan_gn', '김해시 삼계동 생림대로 45-13', 'outdoor', NULL, '055-332-0811', NULL, 'futsal.or.kr', now()),
  ('futsal', '청춘실내풋살장', '경상남도', 'busan_ulsan_gn', '김해시 안곡로 117-1', 'indoor', NULL, '055-311-5855', NULL, 'futsal.or.kr', now()),
  ('futsal', '스포츠파크 축구장', '경상남도', 'busan_ulsan_gn', '남해군 서면 스포츠파크길 74', 'outdoor', 2, '055-860-8665', NULL, 'futsal.or.kr', now()),
  ('futsal', '사천풋살구장', '경상남도', 'busan_ulsan_gn', '사천시 사남면 유천길 123', 'outdoor', 3, '055-852-7980', NULL, 'futsal.or.kr', now()),
  ('futsal', '삼천포풋살구장', '경상남도', 'busan_ulsan_gn', '사천시 용강동', 'outdoor', 3, '055-833-4888', NULL, 'futsal.or.kr', now()),
  ('futsal', '웅상체육공원풋살장', '경상남도', 'busan_ulsan_gn', '양산시 평산동', 'outdoor', 2, '055-379-8585', NULL, 'futsal.or.kr', now()),
  ('futsal', '슛돌이풋살구장', '경상남도', 'busan_ulsan_gn', '진주시 금산면 송백로 268', 'outdoor', 2, '055-763-0407', NULL, 'futsal.or.kr', now()),
  ('futsal', '락랑풋살', '경상남도', 'busan_ulsan_gn', '진주시 금산면 송백로 380', 'outdoor', 2, '055-757-3339', NULL, 'futsal.or.kr', now()),
  ('futsal', '차차풋살장', '경상남도', 'busan_ulsan_gn', '진주시 금산면 금산순환로 34번길 16', 'outdoor', NULL, '070-4123-9665', NULL, 'futsal.or.kr', now()),
  ('futsal', '사라봉축구장', '제주도', 'jeju', '제주시 동문로 169', 'outdoor', 1, '064-728-8548', NULL, 'futsal.or.kr', now()),
  ('futsal', '제주시이호운동장', '제주도', 'jeju', '제주시 오광로6길 58-11', 'outdoor', 1, '064-742-2746', NULL, 'futsal.or.kr', now()),
  ('futsal', '외도운동장', '제주도', 'jeju', '제주시 외도1동 220-1', 'outdoor', 1, '064-728-8545', NULL, 'futsal.or.kr', now()),
  ('futsal', '삼양축구장', '제주도', 'jeju', '제주시 원당북로 45', 'outdoor', 1, '064-721-3391', NULL, 'futsal.or.kr', now())
;